export const links = {
  homeLink: "https://afforai.com/",
  checkMarkCircled: "https://afforai.com/img/icons/check-circle.svg",
  laptopLanding4: "https://afforai.com/img/graphics/laptop-landing-4.png",
  laptopLanding1: "https://afforai.com/img/graphics/laptop-landing-1.png",
  laptopLanding2: "https://afforai.com/img/graphics/laptop-landing-2.png",
  appSumo: "https://afforai.com/img/icons/appsumo.png",
  appSumoLink: "https://appsumo.8odi.net/3eR3xn",
  logo: "https://afforai.com/img/graphics/logo-new-violet.webp",
  badgeOne:
    "https://www.producthunt.com/products/afforai?utm_source=badge-top-post-badge&utm_medium=badge#afforai",
  badgeSvg:
    "https://api.producthunt.com/widgets/embed-image/v1/top-post-badge.svg?post_id=403202&theme=light&period=daily",
  sputnik: "https://afforai.com/img/logos/sputnikatx.png",
  ourStory: "https://afforai.com/our_story",
  affiliate: "https://afforai.getrewardful.com/signup",
  security: "https://afforai.com/security",
  roadmap: "https://trello.com/b/98yNMfwA/afforai-roadmap",
  contact: "https://afforai.com/contact",
  helpCenter: "https://help.afforai.com/",
  apiDocs: "https://afforai.com/documentation",
  terms: "https://afforai.com/terms_of_use",
  privacyPolicy: "https://afforai.com/privacy_policy",
  faceBook: "https://www.facebook.com/groups/afforai",
  linkedIn: "https://linkedin.com/company/afforai/",
  twitter: "https://twitter.com/afforai/",
  blog: "https://medium.com/@alec-afforai",
  pricing: "https://afforai.com/pricing",
  login: "https://afforai.com/login",
  signup: "https://afforai.com/signup",
  streamline: "https://afforai.com/img/graphics/laptop-landing-5.png",
  chooseOne: "https://afforai.com/img/graphics/laptop-landing-6.png",
  chooseTwo: "https://afforai.com/img/graphics/laptop-landing-7.png",
  chooseThree: "https://afforai.com/img/graphics/laptop-landing-8.png",
  chooseFour: "https://afforai.com/img/graphics/laptop-landing-10.png",
  chooseFive: "https://afforai.com/img/graphics/laptop-landing-9.png",
  versatile: "https://afforai.com/img/graphics/laptop-landing-11.png",
  customize: "https://afforai.com/img/graphics/laptop-landing-12.png",
  fastMode: "https://afforai.com/img/icons/fast-forward.svg",
  powerOff: "https://afforai.com/img/icons/power-off.svg",
  plus: "https://afforai.com/img/icons/search-plus.svg",
  lang: "https://afforai.com/img/graphics/laptop-landing-13.png",
  fileWizard: "https://afforai.com/img/graphics/laptop-landing-14.png",
  drive: "https://afforai.com/img/graphics/laptop-landing-15.png",
  accuracyOne: "https://afforai.com/img/graphics/laptop-landing-17.png",
  accuracyTwo: "https://afforai.com/img/graphics/laptop-landing-18.png",
  accuracyThree: "https://afforai.com/img/graphics/laptop-landing-19.png",
  signedBy: "https://afforai.com/img/graphics/laptop-landing-20.png",
  startSavingBg: "https://afforai.com/img/graphics/laptop-landing-16.png",
  testimonialOne: "https://afforai.com/img/testimonials/0-0.webp",
  testimonialTwo: "https://afforai.com/img/testimonials/0-1.webp",
  testimonialThree: "https://afforai.com/img/testimonials/0-2.webp",
  testimonialFour: "https://afforai.com/img/testimonials/0-3.webp",
  testimonialFive: "https://afforai.com/img/testimonials/0-4.webp",
  testimonialSix: "https://afforai.com/img/testimonials/0-5.webp",
  testimonialSeven: "https://afforai.com/img/testimonials/0-6.webp",
  testimonialEight: "https://afforai.com/img/testimonials/1-0.webp",
  testimonialNine: "https://afforai.com/img/testimonials/1-1.webp",
  testimonialTen: "https://afforai.com/img/testimonials/1-2.webp",
  testimonialEleven: "https://afforai.com/img/testimonials/1-3.webp",
  testimonialTwelve: "https://afforai.com/img/testimonials/1-4.webp",
  testimonialThirteen: "https://afforai.com/img/testimonials/1-5.webp",
  testimonialFourteen: "https://afforai.com/img/testimonials/1-6.webp",
  rating: "https://afforai.com/img/graphics/ph-review.webp",
  productHuntLink: "https://www.producthunt.com/products/afforai",
  productHuntIcon: "https://afforai.com/img/icons/producthunt.svg",
};
